version: '3.8'

# Docker Compose with Docker Secrets for maximum security
# Usage: docker-compose -f docker-compose.secrets.yml up --build

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_BUILD_STATIC_GENERATION=true
    restart: unless-stopped
    ports:
      - "3000"
    environment:
      # Production environment
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

      # Database connection using secrets
      - DATABASE_URL=postgresql://invoice_user:$(cat /run/secrets/db_password)@db:5432/invoice_db

      # NextAuth configuration using secrets
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET_FILE=/run/secrets/nextauth_secret
      - ADMIN_PASSWORD_FILE=/run/secrets/admin_password

      # Disable telemetry
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    secrets:
      - db_password
      - nextauth_secret
      - admin_password
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "coolify.managed=true"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      # Database configuration using secrets
      - POSTGRES_USER=invoice_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=invoice_db
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups:rw
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
    networks:
      - app-network
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_db"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

secrets:
  db_password:
    file: ./secrets/db_password.txt
  nextauth_secret:
    file: ./secrets/nextauth_secret.txt
  admin_password:
    file: ./secrets/admin_password.txt

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
